version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DATA_DIR=/tmp/localstack/data
      #- DEBUG=1
    volumes:
      #- "./.localstack:/tmp/localstack"  
      #- "/tmp/localstack:/var/lib/localstac"
      - "./volume:/var/lib/localstack"
      - ./.aws:/docker-entrypoint-initaws.d
      - "./docker/init-aws.sh:/docker-entrypoint-initaws.d/init-aws.sh"  # ready hook